sample_problems = [
    # (ID, Title, Difficulty, Topic, Patterns, URL, Frequency, [Prereqs])

    (1, "Two Sum", "Easy", "Array", ["Hash Table"], "https://leetcode.com/problems/two-sum/", "High", []),
    (2, "Best Time to Buy and Sell Stock", "Medium", "Array", ["Dynamic Programming"], "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "High", [1]),
    (3, "Valid Parentheses", "Easy", "Stack", ["Stack"], "https://leetcode.com/problems/valid-parentheses/", "High", []),
    (4, "Merge Two Sorted Lists", "Easy", "Linked List", ["Two Pointers"], "https://leetcode.com/problems/merge-two-sorted-lists/", "High", [1]),
    (5, "Remove Nth Node From End of List", "Medium", "Linked List", ["Two Pointers"], "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", "High", [4]),
    (6, "Palindrome Linked List", "Easy", "Linked List", ["Two Pointers"], "https://leetcode.com/problems/palindrome-linked-list/", "Medium", [4]),
    (7, "Reverse Linked List", "Easy", "Linked List", ["Iteration"], "https://leetcode.com/problems/reverse-linked-list/", "High", [4]),
    (8, "Maximum Subarray", "Medium", "Array", ["Dynamic Programming"], "https://leetcode.com/problems/maximum-subarray/", "High", [1]),
    (9, "Climbing Stairs", "Easy", "Dynamic Programming", ["Recursion"], "https://leetcode.com/problems/climbing-stairs/", "High", [8]),
    (10, "Coin Change", "Medium", "Dynamic Programming", ["Recursion", "Memoization"], "https://leetcode.com/problems/coin-change/", "High", [9]),
    (11, "Valid Sudoku", "Medium", "Hash Table", ["Hash Table"], "https://leetcode.com/problems/valid-sudoku/", "Medium", [3]),
    (12, "Group Anagrams", "Medium", "Hash Table", ["Hash Table"], "https://leetcode.com/problems/group-anagrams/", "Medium", [11]),
    (13, "Top K Frequent Elements", "Medium", "Hash Table", ["Heap"], "https://leetcode.com/problems/top-k-frequent-elements/", "High", [12]),
    (14, "Product of Array Except Self", "Medium", "Array", ["Dynamic Programming"], "https://leetcode.com/problems/product-of-array-except-self/", "High", [1]),
    (15, "Longest Substring Without Repeating Characters", "Medium", "String", ["Sliding Window"], "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "High", [14]),
    (16, "Longest Palindromic Substring", "Medium", "String", ["Dynamic Programming"], "https://leetcode.com/problems/longest-palindromic-substring/", "High", [15]),
    (17, "Minimum Window Substring", "Medium", "String", ["Sliding Window"], "https://leetcode.com/problems/minimum-window-substring/", "Medium", [15]),
    (18, "Implement Trie (Prefix Tree)", "Medium", "Trie", ["Trie"], "https://leetcode.com/problems/implement-trie-prefix-tree/", "Medium", [16]),
    (19, "Word Search", "Medium", "Backtracking", ["Backtracking"], "https://leetcode.com/problems/word-search/", "Medium", [18]),
    (20, "Number of Islands", "Medium", "Graph", ["Depth-First Search"], "https://leetcode.com/problems/number-of-islands/", "High", [19]),
    (21, "Course Schedule", "Medium", "Graph", ["Topological Sort"], "https://leetcode.com/problems/course-schedule/", "High", [20]),
    (22, "Find the Duplicate Number", "Medium", "Array", ["Two Pointers"], "https://leetcode.com/problems/find-the-duplicate-number/", "High", [1]),
    (23, "Linked List Cycle", "Easy", "Linked List", ["Two Pointers"], "https://leetcode.com/problems/linked-list-cycle/", "High", [5]),
    (24, "Binary Tree Inorder Traversal", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/binary-tree-inorder-traversal/", "High", [7]),
    (25, "Symmetric Tree", "Easy", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/symmetric-tree/", "Medium", [24]),
    (26, "Binary Tree Level Order Traversal", "Medium", "Binary Tree", ["Breadth-First Search"], "https://leetcode.com/problems/binary-tree-level-order-traversal/", "High", [24]),
    (27, "Maximum Depth of Binary Tree", "Easy", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "High", [24]),
    (28, "Validate Binary Search Tree", "Medium", "Binary Search Tree", ["Recursion"], "https://leetcode.com/problems/validate-binary-search-tree/", "High", [24]),
    (29, "Lowest Common Ancestor of a Binary Search Tree", "Medium", "Binary Search Tree", ["Recursion"], "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", "High", [28]),
    (30, "Binary Tree Zigzag Level Order Traversal", "Medium", "Binary Tree", ["Breadth-First Search"], "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/", "Medium", [26]),
    (31, "Construct Binary Tree from Preorder and Inorder Traversal", "Hard", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", "Hard", [24]),
    (32, "Serialize and Deserialize Binary Tree", "Hard", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", "Hard", [24]),
    (33, "Minimum Path Sum", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/minimum-path-sum/", "Medium", [8]),
    (34, "Unique Paths", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/unique-paths/", "High", [9]),
    (35, "Edit Distance", "Hard", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/edit-distance/", "Hard", [9]),
    (36, "Palindrome Partitioning", "Medium", "Backtracking", ["Backtracking"], "https://leetcode.com/problems/palindrome-partitioning/", "Medium", [16]),
    (37, "Combination Sum", "Medium", "Backtracking", ["Backtracking"], "https://leetcode.com/problems/combination-sum/", "High", [20]),
    (38, "Subsets", "Medium", "Backtracking", ["Backtracking"], "https://leetcode.com/problems/subsets/", "High", [7]),
    (39, "Permutations", "Medium", "Backtracking", ["Backtracking"], "https://leetcode.com/problems/permutations/", "High", [7]),
    (40, "Sudoku Solver", "Hard", "Backtracking", ["Backtracking"], "https://leetcode.com/problems/sudoku-solver/", "Hard", [11]),
    (41, "Merge k Sorted Lists", "Hard", "Heap", ["Heap"], "https://leetcode.com/problems/merge-k-sorted-lists/", "Hard", [4, 13]),
    (42, "Find Median from Data Stream", "Hard", "Heap", ["Heap"], "https://leetcode.com/problems/find-median-from-data-stream/", "Hard", [13]),
    (44, "Longest Consecutive Sequence", "Medium", "Union-Find", ["Union-Find"], "https://leetcode.com/problems/longest-consecutive-sequence/", "Medium", [1]),
    (45, "Kth Largest Element in an Array", "Medium", "Heap", ["Heap"], "https://leetcode.com/problems/kth-largest-element-in-an-array/", "High", [1]),
    (46, "Find All Anagrams in a String", "Medium", "String", ["Sliding Window"], "https://leetcode.com/problems/find-all-anagrams-in-a-string/", "Medium", [15]),
    (47, "Word Ladder", "Medium", "Graph", ["Breadth-First Search"], "https://leetcode.com/problems/word-ladder/", "High", [18]),
    (48, "Alien Dictionary", "Hard", "Graph", ["Topological Sort"], "https://leetcode.com/problems/alien-dictionary/", "Hard", [21]),
    (49, "Longest Increasing Subsequence", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/longest-increasing-subsequence/", "High", [8]),
    (50, "Longest Valid Parentheses", "Hard", "String", ["Dynamic Programming"], "https://leetcode.com/problems/longest-valid-parentheses/", "Hard", [3]),
    (51, "Decode Ways", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/decode-ways/", "Medium", [9]),
    (52, "House Robber", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/house-robber/", "High", [8]),
    (53, "House Robber II", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/house-robber-ii/", "Medium", [52]),
    (54, "Burst Balloons", "Hard", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/burst-balloons/", "Hard", [8]),
    (55, "Longest Palindromic Subsequence", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/longest-palindromic-subsequence/", "Medium", [16]),
    (56, "Minimum Size Subarray Sum", "Medium", "Array", ["Sliding Window", "Binary Search"], "https://leetcode.com/problems/minimum-size-subarray-sum/", "Medium", [15]),
    (57, "Insert Interval", "Medium", "Array", ["Two Pointers"], "https://leetcode.com/problems/insert-interval/", "Medium", [1]),
    (58, "Merge Intervals", "Medium", "Array", ["Sorting"], "https://leetcode.com/problems/merge-intervals/", "Medium", [1]),
    (59, "Meeting Rooms II", "Medium", "Heap", ["Heap"], "https://leetcode.com/problems/meeting-rooms-ii/", "Medium", [13]),
    (60, "Median of Two Sorted Arrays", "Hard", "Binary Search", ["Binary Search"], "https://leetcode.com/problems/median-of-two-sorted-arrays/", "Hard", [20]),
    (61, "Regular Expression Matching", "Hard", "String", ["Dynamic Programming"], "https://leetcode.com/problems/regular-expression-matching/", "Hard", [16]),
    (62, "Wildcard Matching", "Hard", "String", ["Dynamic Programming"], "https://leetcode.com/problems/wildcard-matching/", "Hard", [16]),
    (63, "Word Break", "High", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/word-break/", "High", [12]),
    (64, "Unique Binary Search Trees", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/unique-binary-search-trees/", "Medium", [28]),
    (65, "Unique Binary Search Trees II", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/unique-binary-search-trees-ii/", "Medium", [64]),
    (66, "Reorder List", "Medium", "Linked List", ["Two Pointers"], "https://leetcode.com/problems/reorder-list/", "Medium", [5]),
    (67, "LRU Cache", "Hard", "Hash Table", ["Hash Table", "Design"], "https://leetcode.com/problems/lru-cache/", "Hard", [11]),
    (68, "Design Twitter", "Hard", "Heap", ["Heap", "Design"], "https://leetcode.com/problems/design-twitter/", "Hard", [13]),
    (69, "Design In-Memory File System", "Hard", "Trie", ["Trie", "Design"], "https://leetcode.com/problems/design-in-memory-file-system/", "Hard", [18]),
    (70, "Implement Queue using Stacks", "Easy", "Stack", ["Stack"], "https://leetcode.com/problems/implement-queue-using-stacks/", "Easy", [3]),
    (71, "Binary Tree Right Side View", "Medium", "Binary Tree", ["Breadth-First Search"], "https://leetcode.com/problems/binary-tree-right-side-view/", "Medium", [24]),
    (72, "Path Sum", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/path-sum/", "High", [24]),
    (73, "Flatten Binary Tree to Linked List", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/", "Medium", [24]),
    (74, "Count Complete Tree Nodes", "Medium", "Binary Tree", ["Binary Search"], "https://leetcode.com/problems/count-complete-tree-nodes/", "Medium", [24]),
    (75, "Kth Smallest Element in a BST", "Medium", "Binary Search Tree", ["Binary Search"], "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", "Medium", [28]),
    (76, "Binary Tree Maximum Path Sum", "Hard", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/binary-tree-maximum-path-sum/", "Hard", [24]),
    (77, "Sum Root to Leaf Numbers", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/sum-root-to-leaf-numbers/", "Medium", [24]),
    (78, "Populating Next Right Pointers in Each Node", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/", "Medium", [24]),
    (79, "Binary Tree Cameras", "Hard", "Binary Tree", ["Greedy"], "https://leetcode.com/problems/binary-tree-cameras/", "Hard", [24]),
    (80, "All Nodes Distance K in Binary Tree", "Medium", "Binary Tree", ["Breadth-First Search"], "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/", "Medium", [24]),
    (81, "Path Sum II", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/path-sum-ii/", "Medium", [24]),
    (82, "Subarray Sum Equals K", "Medium", "Hash Table", ["Hash Table"], "https://leetcode.com/problems/subarray-sum-equals-k/", "High", [8]),
    (83, "House Robber III", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/house-robber-iii/", "Medium", [52]),
    (84, "Basic Calculator", "Hard", "Math", ["Recursion"], "https://leetcode.com/problems/basic-calculator/", "Hard", [3]),
    (85, "Basic Calculator II", "Medium", "Math", ["Iteration"], "https://leetcode.com/problems/basic-calculator-ii/", "Medium", [3]),
    (86, "Implement Stack using Queues", "Easy", "Stack", ["Queue"], "https://leetcode.com/problems/implement-stack-using-queues/", "Easy", [3]),
    (87, "Binary Search Tree Iterator", "Medium", "Binary Search Tree", ["Iteration"], "https://leetcode.com/problems/binary-search-tree-iterator/", "Medium", [28]),
    (88, "Maximum Product Subarray", "Medium", "Array", ["Dynamic Programming"], "https://leetcode.com/problems/maximum-product-subarray/", "High", [8]),
    (89, "Number of Connected Components in an Undirected Graph", "Medium", "Union-Find", ["Union-Find"], "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/", "Medium", [44]),
    (90, "Spiral Matrix", "Medium", "Array", ["Two Pointers"], "https://leetcode.com/problems/spiral-matrix/", "Medium", [1]),
    (91, "Spiral Matrix II", "Medium", "Array", ["Two Pointers"], "https://leetcode.com/problems/spiral-matrix-ii/", "Medium", [90]),
    (92, "Set Matrix Zeroes", "Medium", "Array", ["Two Pointers"], "https://leetcode.com/problems/set-matrix-zeroes/", "Medium", [1]),
    (93, "Rotate Image", "Medium", "Array", ["Two Pointers"], "https://leetcode.com/problems/rotate-image/", "Medium", [1]),
    (94, "Spiral Matrix III", "Hard", "Array", ["Two Pointers"], "https://leetcode.com/problems/spiral-matrix-iii/", "Hard", [90]),
    (95, "Restore IP Addresses", "Medium", "Backtracking", ["Backtracking"], "https://leetcode.com/problems/restore-ip-addresses/", "Medium", [18]),
    (96, "Restore IP Addresses II", "Hard", "Backtracking", ["Backtracking"], "https://leetcode.com/problems/restore-ip-addresses-ii/", "Hard", [95]),
    (97, "Binary Tree Pruning", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/binary-tree-pruning/", "Medium", [24]),
    (98, "Sum of Two Integers", "Medium", "Math", ["Bit Manipulation"], "https://leetcode.com/problems/sum-of-two-integers/", "Medium", [15]),
    (99, "Single Number", "Medium", "Hash Table", ["Hash Table"], "https://leetcode.com/problems/single-number/", "High", [11]),
    (100, "Majority Element", "Medium", "Hash Table", ["Hash Table"], "https://leetcode.com/problems/majority-element/", "High", [11]),
    (101, "Missing Number", "Medium", "Array", ["Bit Manipulation"], "https://leetcode.com/problems/missing-number/", "High", [1]),
    (102, "Find All Numbers Disappeared in an Array", "Medium", "Array", ["Hash Table"], "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/", "Medium", [1]),
    (103, "Find Peak Element", "Medium", "Binary Search", ["Binary Search"], "https://leetcode.com/problems/find-peak-element/", "Medium", [20]),
    (104, "Search in Rotated Sorted Array", "Medium", "Binary Search", ["Binary Search"], "https://leetcode.com/problems/search-in-rotated-sorted-array/", "Medium", [20]),
    (105, "Find First and Last Position of Element in Sorted Array", "Medium", "Binary Search", ["Binary Search"], "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/", "Medium", [20]),
    (106, "Search a 2D Matrix", "Medium", "Binary Search", ["Binary Search"], "https://leetcode.com/problems/search-a-2d-matrix/", "Medium", [20]),
    (107, "Find Minimum in Rotated Sorted Array", "Medium", "Binary Search", ["Binary Search"], "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", "Medium", [20]),
    (108, "Find Minimum in Rotated Sorted Array II", "Hard", "Binary Search", ["Binary Search"], "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/", "Hard", [107]),
    (109, "Find First Missing Positive", "Hard", "Array", ["Hash Table"], "https://leetcode.com/problems/first-missing-positive/", "Hard", [1]),
    (110, "Rotate List", "Medium", "Linked List", ["Two Pointers"], "https://leetcode.com/problems/rotate-list/", "Medium", [5]),
    (111, "Palindrome Number", "Easy", "Math", ["Math"], "https://leetcode.com/problems/palindrome-number/", "Easy", [3]),
    (112, "Path Sum III", "Hard", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/path-sum-iii/", "Hard", [24]),
    (113, "Path Sum IV", "Hard", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/path-sum-iv/", "Hard", [24]),
    (114, "Flatten Nested List Iterator", "Medium", "Linked List", ["Iteration"], "https://leetcode.com/problems/flatten-nested-list-iterator/", "Medium", [5]),
    (115, "Distinct Subsequences", "Hard", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/distinct-subsequences/", "Hard", [9]),
    (116, "Populating Next Right Pointers in Each Node II", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/", "Medium", [24]),
    (117, "Populating Next Right Pointers in Each Node III", "Hard", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/populating-next-right-pointers-in-each-node-iii/", "Hard", [24]),
    (118, "Sum of Left Leaves", "Easy", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/sum-of-left-leaves/", "Easy", [24]),
    (119, "Binary Tree Tilt", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/binary-tree-tilt/", "Medium", [24]),
    (120, "Binary Tree Cameras", "Hard", "Binary Tree", ["Greedy"], "https://leetcode.com/problems/binary-tree-cameras/", "Hard", [24]),
    (121, "House Robber IV", "Hard", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/house-robber-iv/", "Hard", [52]),
    (122, "Game of Life", "Medium", "Array", ["Simulation"], "https://leetcode.com/problems/game-of-life/", "Medium", [1]),
    (123, "Text Justification", "Hard", "String", ["Greedy"], "https://leetcode.com/problems/text-justification/", "Hard", [15]),
    (124, "Binary Tree Maximum Path Sum II", "Hard", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/binary-tree-maximum-path-sum-ii/", "Hard", [24]),
    (125, "Minimum Domino Rotations For Equal Row", "Medium", "Greedy", ["Greedy"], "https://leetcode.com/problems/minimum-domino-rotations-for-equal-row/", "Medium", [1]),
    (126, "Wiggle Subsequence", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/wiggle-subsequence/", "Medium", [8]),
    (127, "Longest Arithmetic Subsequence", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/longest-arithmetic-subsequence/", "Medium", [8]),
    (128, "Longest Consecutive Path", "Hard", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/longest-consecutive-path/", "Hard", [8, 44]),
    (129, "Longest Substring with At Most Two Distinct Characters", "Medium", "String", ["Sliding Window"], "https://leetcode.com/problems/longest-substring-with-at-most-two-distinct-characters/", "Medium", [15]),
    (130, "Substring with Concatenation of All Words", "Hard", "Hash Table", ["Sliding Window"], "https://leetcode.com/problems/substring-with-concatenation-of-all-words/", "Hard", [15]),
    (131, "Minimum Number of Arrows to Burst Balloons", "Medium", "Greedy", ["Greedy"], "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/", "Medium", [1]),
    (132, "Palindrome Partitioning II", "Hard", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/palindrome-partitioning-ii/", "Hard", [36]),
    (133, "Clone Graph", "Medium", "Graph", ["Depth-First Search"], "https://leetcode.com/problems/clone-graph/", "Medium", [20]),
    (134, "Gas Station", "Medium", "Greedy", ["Greedy"], "https://leetcode.com/problems/gas-station/", "Medium", [1]),
    (135, "Jump Game", "High", "Dynamic Programming", ["Greedy"], "https://leetcode.com/problems/jump-game/", "High", [8]),
    (136, "Jump Game II", "Medium", "Dynamic Programming", ["Greedy"], "https://leetcode.com/problems/jump-game-ii/", "Medium", [135]),
    (137, "Minimum Number of K Consecutive Bit Flips", "Hard", "Greedy", ["Greedy"], "https://leetcode.com/problems/minimum-number-of-k-consecutive-bit-flips/", "Hard", [15]),
    (138, "Copy List with Random Pointer", "Medium", "Linked List", ["Hash Table"], "https://leetcode.com/problems/copy-list-with-random-pointer/", "Medium", [5]),
    (139, "Longest Harmonious Subsequence", "Medium", "Array", ["Hash Table"], "https://leetcode.com/problems/longest-harmonious-subsequence/", "Medium", [1]),
    (140, "Longest Univalue Path", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/longest-univalue-path/", "Medium", [24]),
    (141, "Linked List Cycle II", "Medium", "Linked List", ["Two Pointers"], "https://leetcode.com/problems/linked-list-cycle-ii/", "Medium", [5]),
    (142, "Linked List Cycle III", "Hard", "Linked List", ["Two Pointers"], "https://leetcode.com/problems/linked-list-cycle-iii/", "Hard", [5]),
    (143, "Reorder Data in Log Files", "Medium", "String", ["Sorting"], "https://leetcode.com/problems/reorder-data-in-log-files/", "Medium", [15]),
    (144, "Find All Duplicates in an Array", "Medium", "Array", ["Hash Table"], "https://leetcode.com/problems/find-all-duplicates-in-an-array/", "Medium", [1]),
    (145, "Same Tree", "High", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/same-tree/", "High", [24]),
    (146, "Binary Tree Right Side View II", "Medium", "Binary Tree", ["Breadth-First Search"], "https://leetcode.com/problems/binary-tree-right-side-view-ii/", "Medium", [24]),
    (147, "Subtree of Another Tree", "High", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/subtree-of-another-tree/", "High", [24]),
    (148, "Largest Rectangle in Histogram", "Hard", "Stack", ["Stack"], "https://leetcode.com/problems/largest-rectangle-in-histogram/", "Hard", [3]),
    (149, "Evaluate Reverse Polish Notation", "Medium", "Stack", ["Stack"], "https://leetcode.com/problems/evaluate-reverse-polish-notation/", "Medium", [3]),
    (150, "Basic Calculator III", "Hard", "Math", ["Recursion"], "https://leetcode.com/problems/basic-calculator-iii/", "Hard", [3]),
    (151, "Design Add and Search Words Data Structure", "Medium", "Trie", ["Trie"], "https://leetcode.com/problems/design-add-and-search-words-data-structure/", "Medium", [18]),
    (152, "Sort Colors", "Medium", "Array", ["Two Pointers"], "https://leetcode.com/problems/sort-colors/", "Medium", [1]),
    (153, "Find Peak Element II", "Hard", "Binary Search", ["Binary Search"], "https://leetcode.com/problems/find-peak-element-ii/", "Hard", [20]),
    (154, "Maximum Product of Word Lengths", "Medium", "Hash Table", ["Hash Table"], "https://leetcode.com/problems/maximum-product-of-word-lengths/", "Medium", [12]),
    (155, "Min Stack", "Medium", "Stack", ["Stack"], "https://leetcode.com/problems/min-stack/", "Medium", [3]),
    (156, "Minimum Number of Swaps to Make the Binary String Alternating", "Hard", "Greedy", ["Greedy"], "https://leetcode.com/problems/minimum-number-of-swaps-to-make-the-binary-string-alternating/", "Hard", [15]),
    (157, "Binary Tree Longest Consecutive Sequence", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/binary-tree-longest-consecutive-sequence/", "Medium", [24]),
    (158, "Binary Tree Paths", "Easy", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/binary-tree-paths/", "Easy", [24]),
    (159, "House Robber II", "Medium", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/house-robber-ii/", "Medium", [52]),
    (160, "Binary Tree Level Order Traversal II", "Medium", "Binary Tree", ["Breadth-First Search"], "https://leetcode.com/problems/binary-tree-level-order-traversal-ii/", "Medium", [24]),
    (161, "Flatten Binary Tree to Linked List II", "Hard", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/flatten-binary-tree-to-linked-list-ii/", "Hard", [24]),
    (162, "Binary Tree Level Order Traversal III", "Medium", "Binary Tree", ["Breadth-First Search"], "https://leetcode.com/problems/binary-tree-level-order-traversal-iii/", "Medium", [24]),
    (163, "Binary Tree Maximum Path Sum III", "Hard", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/binary-tree-maximum-path-sum-iii/", "Hard", [24]),
    (164, "Word Ladder II", "Hard", "Graph", ["Breadth-First Search"], "https://leetcode.com/problems/word-ladder-ii/", "Hard", [18]),
    (165, "Word Search II", "Hard", "Backtracking", ["Backtracking"], "https://leetcode.com/problems/word-search-ii/", "Hard", [18]),
    (166, "Shortest Path in Binary Matrix", "Medium", "Graph", ["Breadth-First Search"], "https://leetcode.com/problems/shortest-path-in-binary-matrix/", "Medium", [20]),
    (167, "Number of Distinct Islands", "Medium", "Graph", ["Depth-First Search"], "https://leetcode.com/problems/number-of-distinct-islands/", "Medium", [20]),
    (168, "Shortest Path to Get All Keys", "Hard", "Graph", ["Breadth-First Search"], "https://leetcode.com/problems/shortest-path-to-get-all-keys/", "Hard", [20]),
    (169, "Word Break II", "Hard", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/word-break-ii/", "Hard", [63]),
    (170, "Minimum Cost to Connect Sticks", "Medium", "Greedy", ["Greedy"], "https://leetcode.com/problems/minimum-cost-to-connect-sticks/", "Medium", [13]),
    (171, "Basic Calculator IV", "Hard", "Math", ["Recursion"], "https://leetcode.com/problems/basic-calculator-iv/", "Hard", [3]),
    (172, "Minimum Cost to Merge Stones", "Hard", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/minimum-cost-to-merge-stones/", "Hard", [8]),
    (173, "Robot Return to Origin", "Easy", "Math", ["Math"], "https://leetcode.com/problems/robot-return-to-origin/", "Easy", []),
    (174, "Shortest Palindrome", "Hard", "String", ["Dynamic Programming"], "https://leetcode.com/problems/shortest-palindrome/", "Hard", [16]),
    (175, "Minimum Number of Vertices to Reach All Nodes", "Hard", "Graph", ["Topological Sort"], "https://leetcode.com/problems/minimum-number-of-vertices-to-reach-all-nodes/", "Hard", [21]),
    (176, "Walls and Gates", "Medium", "Array", ["Breadth-First Search"], "https://leetcode.com/problems/walls-and-gates/", "Medium", [15]),
    (177, "Sliding Window Median", "Hard", "Heap", ["Heap", "Sliding Window"], "https://leetcode.com/problems/sliding-window-median/", "Hard", [15, 13]),
    (178, "Heaters", "Medium", "Binary Search", ["Binary Search"], "https://leetcode.com/problems/heaters/", "Medium", [20]),
    (179, "Kth Smallest Element in a Sorted Matrix", "Medium", "Heap", ["Heap"], "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/", "Medium", [13]),
    (180, "Rearrange String k Distance Apart", "Hard", "Greedy", ["Greedy"], "https://leetcode.com/problems/rearrange-string-k-distance-apart/", "Hard", [15, 13]),
    (181, "Rearrange Words in a Sentence", "Easy", "String", ["Sorting"], "https://leetcode.com/problems/rearrange-words-in-sentence/", "Easy", []),
    (182, "Minimum Number of Frogs Croaking", "Medium", "String", ["Greedy"], "https://leetcode.com/problems/minimum-number-of-frogs-croaking/", "Medium", [15]),
    (183, "Count Good Nodes in Binary Tree", "Medium", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/count-good-nodes-in-binary-tree/", "Medium", [24]),
    (184, "Find All Numbers with Even Number of Digits", "Easy", "Math", ["Math"], "https://leetcode.com/problems/find-all-numbers-with-even-number-of-digits/", "Easy", [1]),
    (185, "Kth Smallest Element in a BST", "Medium", "Binary Search Tree", ["Binary Search"], "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", "Medium", [28]),
    (186, "Path Sum IV", "Hard", "Binary Tree", ["Recursion"], "https://leetcode.com/problems/path-sum-iv/", "Hard", [24]),
    (187, "Max Area of Island", "Medium", "Graph", ["Depth-First Search"], "https://leetcode.com/problems/max-area-of-island/", "Medium", [20]),
    (188, "Contiguous Array", "Medium", "Hash Table", ["Hash Table"], "https://leetcode.com/problems/contiguous-array/", "Medium", [1]),
    (189, "Spiral Matrix IV", "Hard", "Array", ["Two Pointers"], "https://leetcode.com/problems/spiral-matrix-iv/", "Hard", [90]),
    (190, "Dungeon Game", "Hard", "Dynamic Programming", ["Dynamic Programming"], "https://leetcode.com/problems/dungeon-game/", "Hard", [8]),
    (191, "Number of Enclaves", "Medium", "Graph", ["Depth-First Search"], "https://leetcode.com/problems/number-of-enclaves/", "Medium", [20]),
    (192, "Split Array Largest Sum", "Hard", "Binary Search", ["Binary Search"], "https://leetcode.com/problems/split-array-largest-sum/", "Hard", [20]),
    (193, "Find the Celebrity", "Medium", "Graph", ["Topological Sort"], "https://leetcode.com/problems/find-the-celebrity/", "Medium", [21]),
    (195, "Product of Array Except Self II", "Hard", "Array", ["Two Pointers"], "https://leetcode.com/problems/product-of-array-except-self-ii/", "Hard", [1]),
    (196, "Partition Labels", "Medium", "Greedy", ["Greedy"], "https://leetcode.com/problems/partition-labels/", "Medium", [15]),
    (197, "Longest Mountain in Array", "Medium", "Array", ["Two Pointers"], "https://leetcode.com/problems/longest-mountain-in-array/", "Medium", [1]),
    (198, "Product of Array Except Self III", "Hard", "Array", ["Two Pointers"], "https://leetcode.com/problems/product-of-array-except-self-iii/", "Hard", [1]),
    (199, "Longest Well-Performing Interval", "Medium", "Array", ["Stack"], "https://leetcode.com/problems/longest-well-performing-interval/", "Hard", [3]),
    (200, "Contains Duplicate", "Easy", "Array", ["Hash Table"], "https://leetcode.com/problems/contains-duplicate/", "High", []),
]
